### ISSUE TITLE
Crash with Cblizdata

### ISSUE THREAD

**Issue by Pychnight** [k0rd/Custom-Monsters-Plugin--Tshock-#13]
3/30/2012 8:08:23 PM
System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomMonsters.CustomMonstersPlugin.CBlitz(Single X, Single Y, Int32 blitzstyle, String SCMType)
   at CustomMonsters.CustomMonstersPlugin.HandleCBlitzers()
   at CustomMonsters.CustomMonstersPlugin.OnUpdate()
   at System.Action.Invoke()
   at Hooks.GameHooks.OnUpdate(Boolean pre)
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.Main(String[] args)

this is what the line looked like

cblitzdata:flying unicorn:3:240

it references to itself

**Comment by Olink** [comment]
fixed
