### ISSUE TITLE
Crash ReplaceMonsters

### ISSUE THREAD

**Issue by Pychnight** [k0rd/Custom-Monsters-Plugin--Tshock-#17]
4/3/2012 9:07:47 PM
System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomMonsters.CustomMonstersPlugin.<ReplaceMonsters>b__50(CustomMonsterType monstertype)
   at System.Collections.Generic.List`1.FindAll(Predicate`1 match)
   at CustomMonsters.CustomMonstersPlugin.ReplaceMonsters()
   at CustomMonsters.CustomMonstersPlugin.OnUpdate()
   at System.Action.Invoke()
   at Hooks.GameHooks.OnUpdate(Boolean pre)
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.Main(String[] args)

**Comment by Olink** [comment]
What exactly does replace monster do? The code i sless than clear

**Comment by Pychnight** [comment]
it basically Find the monster id you enter then replaces all of the monsters of that type with the Custom monster you designed to replace that monster.

it's works last time, i checked. i have not tested for this crash again yet. I'm unsure if this issue still exists.
